/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestIndexRouteImport } from './routes/guest/index'
import { Route as GuestDashboardRouteImport } from './routes/guest/dashboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as GuestSessionsNewRouteImport } from './routes/guest/sessions.new'
import { Route as GuestSessionsIdRouteImport } from './routes/guest/sessions.$id'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions.new'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestDashboardRoute = GuestDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuestSessionsNewRoute = GuestSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSessionsIdRoute = GuestSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guest': typeof GuestRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest/': typeof GuestIndexRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/guest/sessions/$id': typeof GuestSessionsIdRoute
  '/guest/sessions/new': typeof GuestSessionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest': typeof GuestIndexRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/guest/sessions/$id': typeof GuestSessionsIdRoute
  '/guest/sessions/new': typeof GuestSessionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/guest': typeof GuestRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest/': typeof GuestIndexRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/guest/sessions/$id': typeof GuestSessionsIdRoute
  '/guest/sessions/new': typeof GuestSessionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/login'
    | '/dashboard'
    | '/guest/dashboard'
    | '/guest/'
    | '/sessions/$id'
    | '/sessions/new'
    | '/guest/sessions/$id'
    | '/guest/sessions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/guest/dashboard'
    | '/guest'
    | '/sessions/$id'
    | '/sessions/new'
    | '/guest/sessions/$id'
    | '/guest/sessions/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/guest'
    | '/login'
    | '/_authenticated/dashboard'
    | '/guest/dashboard'
    | '/guest/'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/new'
    | '/guest/sessions/$id'
    | '/guest/sessions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/': {
      id: '/guest/'
      path: '/'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/guest/dashboard': {
      id: '/guest/dashboard'
      path: '/dashboard'
      fullPath: '/guest/dashboard'
      preLoaderRoute: typeof GuestDashboardRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/guest/sessions/new': {
      id: '/guest/sessions/new'
      path: '/sessions/new'
      fullPath: '/guest/sessions/new'
      preLoaderRoute: typeof GuestSessionsNewRouteImport
      parentRoute: typeof GuestRoute
    }
    '/guest/sessions/$id': {
      id: '/guest/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/guest/sessions/$id'
      preLoaderRoute: typeof GuestSessionsIdRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestDashboardRoute: typeof GuestDashboardRoute
  GuestIndexRoute: typeof GuestIndexRoute
  GuestSessionsIdRoute: typeof GuestSessionsIdRoute
  GuestSessionsNewRoute: typeof GuestSessionsNewRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestDashboardRoute: GuestDashboardRoute,
  GuestIndexRoute: GuestIndexRoute,
  GuestSessionsIdRoute: GuestSessionsIdRoute,
  GuestSessionsNewRoute: GuestSessionsNewRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
